home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 2021.6.3
    pullPolicy: IfNotPresent

  env:
    TZ: America/Chicago

  service:
    main:
      ports:
        http:
          port: 8123

  ingress:
    main:
      enabled: true
      primary: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: false
        cert-manager.io/issuer: letsencrypt-staging
      hosts:
      - host: home-assistant.abrmanlabs.com
              
    tls:
       - secretName: chart-example-tls
         hosts:
           - home-assistant.abrmanlabs.com

  hostNetwork: true

  dnsPolicy: ClusterFirstWithHostNet

  persistence:
    config:
      enabled: true

  # -- Enable and configure postgresql database subchart under this key.
  #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
  # @default -- See values.yaml
  postgresql:
    enabled: true
    postgresqlUsername: home-assistant
    postgresqlPassword: home-assistant-pass
    postgresqlDatabase: home-assistant
    persistence:
      enabled: true
      storageClass: "longhorn"

  metrics:
    # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
    # @default -- See values.yaml
    enabled: false
    serviceMonitor:
      interval: 1m
      scrapeTimeout: 30s
      labels: {}
      ## See https://www.home-assistant.io/docs/authentication/ for where to find
      ## long lived access token creation under your account profile, which is
      ## needed to monitor Home Assistant
      # bearerTokenSecret:
      #   name: ""
      #   key: ""

    # -- Enable and configure Prometheus Rules for the chart under this key.
    # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
      # -- Configure additionial rules for the chart under this key.
      # @default -- See prometheusrules.yaml
      rules: []
        # - alert: HomeAssistantAbsent
        #   annotations:
        #     description: Home Assistant has disappeared from Prometheus service discovery.
        #     summary: Home Assistant is down.
        #   expr: |
        #     absent(up{job=~".*home-assistant.*"} == 1)
        #   for: 5m
        #   labels:
        #     severity: critical
