home-assistant:
  image:
    repository: homeassistant/home-assistant
    tag: 2021.6.3
    pullPolicy: IfNotPresent
    
  env:
    TZ: America/Chicago
    
  service:
    main:
      ports:
        http:
          port: 8123

  ingress:
    main:
      enabled: true
      primary: true
      nameOverride:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "false"
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
      -  # -- Host address. Helm template can be passed.
          host: home-assistant.abrmanlabs.com
          paths:
            -  # -- Path.  Helm template can be passed.
              path: /
              pathType: Prefix
              service:
                name: 
                port: 8123

      tls:
        - secretName: hass-tls-staging-v3
          hosts:
           - home-assistant.abrmanlabs.com
           
  persistence:
    config:
      enabled: true
      storageClass: "longhorn"
      accessModes:
      - ReadWriteOnce
      size: 1Gi
      selector:
        matchLabels:
          app: home-assistant
  
  postgresql:
    enabled: true
    postgresqlUsername: home-assistant
    postgresqlPassword: home-assistant-pass
    postgresqlDatabase: home-assistant
    persistence:
      enabled: true
      storageClass: "longhorn"
      mountPath: /bitnami/postgresql
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      selector: {}
