---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: originals
  labels:
    app: photoprism
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photoprism
  labels:
    app: photoprism
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
