# This values.yaml file contains the values needed to enable HA mode.
# Usage:
#   helm install -f values.yaml -f values-ha.yaml

linkerd2:

  identityTrustAnchorsPEM: |
    ca.crt
  identity:
    # -- If the linkerd-identity-trust-roots ConfigMap has already been created
    externalCA: false
    issuer:
      scheme: linkerd.io/tls

      # -- Amount of time to allow for clock skew within a Linkerd cluster
      clockSkewAllowance: 20s

      # -- Expiration timestamp for the issuer certificate. It must be provided during install. Must match the expiry date in crtPEM
      crtExpiry: 2022-10-05T18L11:03Z

      # -- Amount of time for which the Identity issuer should certify identity
      issuanceLifetime: 24h0m0s

      # -- Which scheme is used for the identity issuer secret format
      tls:
        # -- Issuer certificate (ECDSA). It must be provided during install.
        crtPEM: |
          issuer.crt
        # -- Key for the issuer certificate (ECDSA). It must be provided during
        # install
        keyPEM: |
          issuer.key

  enablePodAntiAffinity: true

  # proxy configuration
  proxy:
    resources:
      cpu:
        request: 100m
     memory:
        limit: 250Mi
        request: 20Mi

  # controller configuration
  controllerReplicas: 3
  controllerResources: &controller_resources
    cpu: &controller_resources_cpu
      limit: ""
      request: 100m
    memory:
      limit: 250Mi
      request: 50Mi
  destinationResources: *controller_resources

  # identity configuration
  identityResources:
    cpu: *controller_resources_cpu
    memory:
      limit: 250Mi
      request: 10Mi

  # heartbeat configuration
  heartbeatResources: *controller_resources

  # proxy injector configuration
  proxyInjectorResources: *controller_resources
  webhookFailurePolicy: Fail

  # service profile validator configuration
  spValidatorResources: *controller_resources
  
  cniEnabled:
    true
