apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless-ng
  name: paperless-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ng
  template:
    metadata:
      labels:
        app: paperless-ng
    spec:
      containers:
      - image: ghcr.io/linuxserver/paperless-ng
        name: paperless-ng
        app: longhorn-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/Chicago"
