linkerd2-cni:
  # -- CNI plugin plane namespace
  namespace: linkerd-cni
  # -- Whether to create the CNI plugin plane namespace or not
  installNamespace: true
  # -- Inbound port for the proxy container
  inboundProxyPort: 4143
  # -- Outbound port for the proxy container
  outboundProxyPort: 4140
  # -- Default set of inbound ports to skip via iptables
  ignoreInboundPorts: ""
  # -- Default set of outbound ports to skip via iptables
  ignoreOutboundPorts: ""
  # -- Admin port for the proxy container
  proxyAdminPort: 4191
  # -- Control port for the proxy container
  proxyControlPort: 4190
  # -- Docker image for the CNI plugin
  cniPluginImage:   "cr.l5d.io/linkerd/cni-plugin"
  # -- Tag for the CNI container Docker image
  cniPluginVersion: stable-2.11.1
  # -- Log level for the CNI plugin
  logLevel:         info
  # -- Ports to redirect to proxy
  portsToRedirect:  ""
  # -- User id under which the proxy shall be ran
  proxyUID:         2102
  # -- Directory on the host where the CNI plugin binaries reside
  destCNINetDir:    "/etc/cni/net.d"
  # -- Directory on the host where the CNI configuration will be placed
  destCNIBinDir:    "/opt/cni/bin"
  # -- Configures the CNI plugin to use the -w flag for the iptables command
  useWaitFlag:      false
  # -- Kubernetes priorityClassName for the CNI plugin's Pods
  priorityClassName: ""
  enablePSP: false

