apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:  
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - helloworld.abrmanlabs.com
    secretName: nginx-hello-tls-staging
  rules:
  - host: helloworld.abrmanlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
