apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "1.0"

dependencies:
- name: ingress-nginx
  version: 1.1.0
  repository: https://kubernetes.github.io/ingress-nginx
