netdata:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - netdata.abrmanlabs.com
  #  tls:
  #    - secretName: netdata-tls
  #      hosts:
  #        - netdata.k8s.local
  parent:

    database:
      persistence: true
      ## Set '-' as the storageclass to get a volume from the default storage class.
      storageclass: longhorn
      volumesize: 2Gi

    alarms:
      persistence: true
      ## Set '-' as the storageclass to get a volume from the default storage class.
      storageclass: longhorn
      volumesize: 1Gi
