longhorn:
  service:
    ui:
      type: ClusterIP
      nodePort: null
    manager:
      type: ClusterIP
      nodePort: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.abrmanlabs.com
    tls: true
    tlsSecret: longhorn-tls-prod
    annotations: 
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
