apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.5.3
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    syncOptions:
      - CreateNamespace=true
