apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuers
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cluster-issuers
    repoURL: https://github.com/abrmans/argocd-bootstrap-git
    targetRevision: HEAD
