apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  destination:
    namespace: home-assistant
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: home-assistant
    repoURL: https://github.com/abrmans/home-assistant
    targetRevision: HEAD
