apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd2-cni
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: linkerd2-cni
    repoURL: https://github.com/abrmans/argocd-bootstrap-git/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
