apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz-ingress
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkerd-viz
  project: default
  source:
    path: linkerd-main-ingress
    repoURL: https://github.com/abrmans/private-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
