apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-cni
spec:
  destination:
    namespace: linkerd-cni
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: linkerd-cni
    repoURL: https://github.com/abrmans/linkerd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
