apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monica
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monica
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monica
    repoURL: https://github.com/abrmans/private-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
