apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-nginx
spec:
  destination:
    namespace: oauth2-proxy
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: kustomize-nginx
    repoURL: https://github.com/abrmans/argocd-bootstrap-git/
    targetRevision: HEAD
