apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  destination:
    namespace: oauth2-proxy
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: keycloak
    repoURL: https://github.com/abrmans/keycloak
    targetRevision: HEAD
