apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
spec:
  destination:
    namespace: paperless
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: paperless
    repoURL: https://github.com/abrmans/argocd-bootstrap-git/
    targetRevision: HEAD
