apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: kustomize-pgadmin
    repoURL: https://github.com/abrmans/pgadmin
    targetRevision: HEAD
