apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
spec:
  destination:
    namespace: vaultwarden
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: vaultwarden
    repoURL: https://github.com/abrmans/vaultwarden
    targetRevision: HEAD
