kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-config
  labels:
    app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  labels:
    app: smokeping
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
