esphome:
  service:
    main:
      enabled: true
      primary: true
      type: ClusterIP
      annotations:
        name: esphome
      ports:
        http:
          enabled: true
          primary: true
          port: 6052
        
  ingress:
    main:
      enabled: true
      primary: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "false"
        cert-manager.io/issuer: "letsencrypt-staging"
      hosts:
        -  host: esphome.abrmanlabs.com
           paths:
              path: /
              pathType: Prefix
              service:
                name: esphome
                port: 6052
      tls:
       - secretName: esphome-tls-staging
         hosts:
           - esphome.abrmanlabs.com
