esphome:
  service:
    main:
      ports:
        http:
          port: 6052
        
  ingress:
    main:
      enabled: true
      primary: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "false"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      -  # -- Host address. Helm template can be passed.
          host: esphome.abrmanlabs.com
          paths:
            -  # -- Path.  Helm template can be passed.
              path: /
              pathType: Prefix
              service:
                name: 
                port: 6052
      tls:
        - secretName: esphome-tls-secret-production
          hosts:
            - esphome.abrmanlabs.com
