apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: "https://authentication.int.abrmanlabs.com/oauth2/start?rd=https://$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-url: "http://authentication.int.abrmanlabs.com/oauth2/auth"
  name: nginx
spec:
  rules:
  - hosts: nginx.int.abrmanlabs.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx
            port:
              number: 80
