cert-manager:
  installCRDs: true
  serviceAccount:
    annotations:
      linkerd.io/inject: enabled
  podAnnotations:
    linkerd.io/inject: enabled
  deploymentAnnotations:
    linkerd.io/inject: enabled
